# Change these first
owner: DaalBot # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API
    url: https://api.daalbot.xyz/get/test/ping
  - name: Bot
    url: https://bot.daalbot.xyz/get/test/ping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.daalbot.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://media.piny.dev/daalbot/website/logo.svg
  name: DaalBot Status
  theme: night
  navbar:
    - title: Home
      href: https://daalbot.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
